id_joint:
  1  : r_arm_sh_p1
  2  : l_arm_sh_p1
  3  : r_arm_sh_r
  4  : l_arm_sh_r
  5  : r_arm_sh_p2
  6  : l_arm_sh_p2
  7  : r_arm_el_y
  8  : l_arm_el_y
  9  : r_arm_wr_r
  10 : l_arm_wr_r
  11 : r_arm_wr_y
  12 : l_arm_wr_y
  13 : r_arm_wr_p
  14 : l_arm_wr_p
  15 : r_leg_hip_y
  16 : l_leg_hip_y
  17 : r_leg_hip_r
  18 : l_leg_hip_r
  19 : r_leg_hip_p
  20 : l_leg_hip_p
  21 : r_leg_kn_p
  22 : l_leg_kn_p
  23 : r_leg_an_p
  24 : l_leg_an_p
  25 : r_leg_an_r
  26 : l_leg_an_r
  27 : torso_y
  28 : head_y
  29 : head_p
  30 : l_arm_grip
  31 : r_arm_grip
module_list: [none, walking_module, manipulation_module, head_control_module, base_module, action_module, gripper_module]
module_button:
  1 : none
  2 : manipulation_module
  3 : walking_module
  4 : head_control_module
  5 : action_module
  6 : gripper_module
